---
- name: Server patching
  hosts: dev
  gather_facts: no
  strategy: free
  become: true
  become_user: root
  become_method: sudo

  tasks:
  - name: disabling firewall service
    service:
     name: firewalld
     state: stopped

  - name: install httpd package
    yum:
     name: httpd
     state: latest

  - name: start httpd service
    service:
      name: httpd
      state: started

  - name: copy index file 
    copy:
      src: ./index.html
      dest: /var/www/html
