- name: Install mysqldb
  yum:
   name: "{{ item }}"
   state: installed
  with_items:
   - mariadb
   - mariadb-libs
   - mariadb-server
   - MySQL-python

- name: Start mysql service
  service:
   name: mariadb
   state: started
   enabled: yes

- name: Create App Database
  mysql_db: 
   name: "{{ db_name }}" 
   state: present

- name: Create DB user
  mysql_user:
   name: "{{ db_user }}"
   password: "{{ db_user_password }}"
   priv: '*.*:ALL'
   state: present
