- name: Install Httpd Package
  yum:
    name: httpd
    state: latest

- name: Copy Files
  copy:
     src: /home/ansible/playbooks/web/files/
     dest: /var/www/html
  notify: restart httpd

- name: Start httpd service
  service:
     name: httpd
     state: started
     enabled: yes
